### PR TITLE
Remove Integrity Checks from generator

### PR DESCRIPTION
**Pull request by xKiraiChan**
I stripped out the code that does the actual checking but left behind the rest.
I have tested my changes and they worked.

### CODE REVIEW

**Comment by forever-and-a-day** [comment]
FavCat-Restored is not obfuscated. While it's up to FelkonEx obviously, i'd personally want to avoid supporting melonloaders that allow this code to be loaded, especially when many of the mods that load obfuscated code are known to include auth token loggers and RATs. The goal of this project is *only* to restore the avatar favorating functionality of the original FavCat.

**Comment by xKiraiChan** [comment]
This code prevents it from running on [BepInEx](https://github.com/BepInEx/BepInEx). A loader is a loader, not a security tool.

**Comment by FelkonEXE** [comment]
I personally don't care what loader anyone uses, and hey I've been all for someone doing a PR to remove the checks.
**_At the end of the day, anyone can use anything they want._** They should know the risks associated with what they use.
I'll look at testing & merging this change over the next day,

**Comment by mixerrules** [comment]
PLZ I NEED BEPINEX IN MY LIFE

**Pull request closed without merging**
